import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { LifeBuoy, MessageSquarePlus } from 'lucide-react'
import { useState } from 'react'
import { Button, Card, Input } from '../../components/ui'
import { api } from '../../lib/api'

type Ticket={_id:string;subject:string;message:string;category:string;priority:string;status:string;resolution?:string;resolvedAt?:string|null;createdAt:string;updatedAt:string}
const initial={subject:'',message:'',category:'technical',priority:'normal'}
export function SupportPage(){
  const client=useQueryClient();const [form,setForm]=useState(initial);const [notice,setNotice]=useState('')
  const query=useQuery({queryKey:['support-tickets'],queryFn:async()=>{const response=await api.get<{success:true;data:Ticket[]}>('/users/support-tickets');return response.data.data}})
  const mutation=useMutation({mutationFn:()=>api.post('/users/support-tickets',form),onSuccess:async()=>{setForm(initial);setNotice('Support ticket created. The administration team can now review it.');await client.invalidateQueries({queryKey:['support-tickets']})}})
  return <div className="platform-support-page"><div className="page-header"><div><span className="eyebrow">Help and support</span><h1>Support centre</h1><p className="muted">Report account, booking, payment, or technical problems and track the resolution.</p></div><LifeBuoy/></div>{notice&&<div className="alert success">{notice}</div>}<div className="platform-support-grid"><Card><div className="student-card-heading"><span className="student-card-icon"><MessageSquarePlus/></span><div><h3>Create a ticket</h3><p className="muted">Include enough detail for the admin team to reproduce the issue.</p></div></div><form className="form" onSubmit={(event)=>{event.preventDefault();mutation.mutate()}}><label>Subject<Input required minLength={3} maxLength={180} value={form.subject} onChange={(event)=>setForm(value=>({...value,subject:event.target.value}))}/></label><div className="form-grid"><label>Category<select className="input" value={form.category} onChange={(event)=>setForm(value=>({...value,category:event.target.value}))}>{['account','booking','payment','technical','other'].map(value=><option key={value}>{value}</option>)}</select></label><label>Priority<select className="input" value={form.priority} onChange={(event)=>setForm(value=>({...value,priority:event.target.value}))}>{['low','normal','high','urgent'].map(value=><option key={value}>{value}</option>)}</select></label></div><label>What happened?<textarea className="input admin-textarea admin-textarea-tall" required minLength={10} maxLength={3000} value={form.message} onChange={(event)=>setForm(value=>({...value,message:event.target.value}))}/></label>{mutation.isError&&<div className="alert error">Could not create the ticket. Please review the details and try again.</div>}<Button disabled={mutation.isPending}>{mutation.isPending?'Submitting…':'Submit ticket'}</Button></form></Card><Card><h3>Your tickets</h3>{query.isLoading?<div className="skeleton"/>:query.isError?<p className="muted">Could not load tickets.</p>:query.data?.length===0?<div className="student-empty-state"><p>No support tickets yet.</p></div>:<div className="platform-ticket-list">{query.data?.map(ticket=><div className="platform-ticket" key={ticket._id}><div className="row-between"><strong>{ticket.subject}</strong><span className={`badge badge-${['resolved','closed'].includes(ticket.status)?'success':ticket.priority==='urgent'?'danger':'warning'}`}>{ticket.status.replaceAll('_',' ')}</span></div><p>{ticket.message}</p><small>{ticket.category} · {ticket.priority} · {new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(ticket.createdAt))}</small>{ticket.resolution&&<div className="platform-ticket-resolution"><strong>Resolution</strong><p>{ticket.resolution}</p></div>}</div>)}</div>}</Card></div></div>
}
