import { zodResolver } from '@hookform/resolvers/zod'
import axios from 'axios'
import { ArrowRight, BrainCircuit, CheckCircle2, GraduationCap, UserRoundCheck } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { Button, Card, Input } from '../../components/ui'
import { api } from '../../lib/api'
import { useAuthStore } from '../../stores/auth.store'

const loginSchema=z.object({email:z.string().email(),password:z.string().min(1)})
type Login=z.infer<typeof loginSchema>
export function LoginPage(){const user=useAuthStore(s=>s.user);const setSession=useAuthStore(s=>s.setSession);const nav=useNavigate();const loc=useLocation();const [error,setError]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<Login>({resolver:zodResolver(loginSchema)});if(user)return <Navigate to={`/${user.role}/dashboard`} replace/>;const submit=handleSubmit(async(v)=>{try{setError('');const r=await api.post('/auth/login',v);setSession(r.data.data.accessToken,r.data.data.user);nav((loc.state as {from?:string}|null)?.from??`/${r.data.data.user.role}/dashboard`)}catch(e){setError(axios.isAxiosError(e)?e.response?.data?.error?.message??'Login failed':'Login failed')}});return <AuthShell title="Welcome back" subtitle="Continue your learning journey"><form onSubmit={submit} className="form"><label>Email<Input type="email" placeholder="you@example.com" {...register('email')}/>{errors.email&&<small className="field-error">{errors.email.message}</small>}</label><label>Password<Input type="password" placeholder="••••••••" {...register('password')}/></label>{error&&<div className="alert error">{error}</div>}<Button disabled={isSubmitting}>{isSubmitting?'Signing in...':'Login'} <ArrowRight size={18}/></Button><div className="form-links"><Link to="/forgot-password">Forgot password?</Link><Link to="/register">Create account</Link></div></form></AuthShell>}

const registerSchema=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8).regex(/[A-Z]/).regex(/[a-z]/).regex(/[0-9]/),role:z.enum(['student','teacher']),gradeLevel:z.string().optional(),qualification:z.string().optional(),experienceYears:z.number().min(0).optional(),hourlyRate:z.number().min(0).optional()})
type Register=z.infer<typeof registerSchema>
export function RegisterPage(){const setSession=useAuthStore(s=>s.setSession);const nav=useNavigate();const [error,setError]=useState('');const {register,watch,handleSubmit,formState:{errors,isSubmitting}}=useForm<Register>({resolver:zodResolver(registerSchema),defaultValues:{role:'student',experienceYears:0,hourlyRate:0}});const role=watch('role');const submit=handleSubmit(async(v)=>{try{setError('');const body={name:v.name,email:v.email,password:v.password,role:v.role,gradeLevel:v.gradeLevel,preferredSubjects:[],teacher:v.role==='teacher'?{bio:'',qualification:v.qualification??'',experienceYears:v.experienceYears??0,hourlyRate:v.hourlyRate??0,timezone:'Asia/Kolkata',subjects:[]}:undefined};const r=await api.post('/auth/register',body);setSession(r.data.data.accessToken,r.data.data.user);nav(`/${v.role}/dashboard`)}catch(e){setError(axios.isAxiosError(e)?e.response?.data?.error?.message??'Registration failed':'Registration failed')}});return <AuthShell title="Create your account" subtitle="Choose your role and get started"><form onSubmit={submit} className="form"><div className="role-tabs"><label className={role==='student'?'role-card selected':'role-card'}><input type="radio" value="student" {...register('role')}/><GraduationCap/>Student</label><label className={role==='teacher'?'role-card selected':'role-card'}><input type="radio" value="teacher" {...register('role')}/><UserRoundCheck/>Teacher</label></div><label>Full name<Input {...register('name')}/>{errors.name&&<small className="field-error">{errors.name.message}</small>}</label><label>Email<Input type="email" {...register('email')}/></label><label>Password<Input type="password" {...register('password')}/><small className="muted">8+ characters with uppercase, lowercase and number</small></label>{role==='student'?<label>Grade/Class<Input placeholder="Example: 10" {...register('gradeLevel')}/></label>:<><label>Qualification<Input {...register('qualification')}/></label><div className="form-grid"><label>Experience<Input type="number" {...register('experienceYears',{valueAsNumber:true})}/></label><label>Hourly rate ₹<Input type="number" {...register('hourlyRate',{valueAsNumber:true})}/></label></div></>}{error&&<div className="alert error">{error}</div>}<Button disabled={isSubmitting}>{isSubmitting?'Creating...':'Register'} <ArrowRight size={18}/></Button><p className="center muted">Already registered? <Link to="/login">Login</Link></p></form></AuthShell>}

export function ForgotPasswordPage(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();await api.post('/auth/forgot-password',{email});setSent(true)};return <AuthShell title="Forgot password" subtitle="We will send a six-digit reset OTP"><form onSubmit={submit} className="form">{sent?<div className="success-panel"><CheckCircle2/><h3>Check your email</h3><p className="muted">In development, the OTP appears in the API console.</p><Link to={`/reset-password?email=${encodeURIComponent(email)}`}>Enter OTP</Link></div>:<><label>Email<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><Button>Send OTP</Button></>}<Link to="/login">Back to login</Link></form></AuthShell>}
export function ResetPasswordPage(){const q=new URLSearchParams(location.search);const [email,setEmail]=useState(q.get('email')??'');const [otp,setOtp]=useState('');const [newPassword,setPassword]=useState('');const [done,setDone]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();await api.post('/auth/reset-password',{email,otp,newPassword});setDone(true)};return <AuthShell title="Reset password" subtitle="Use the OTP sent to your email">{done?<div className="success-panel"><CheckCircle2/><h3>Password updated</h3><Link to="/login">Go to login</Link></div>:<form onSubmit={submit} className="form"><label>Email<Input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>OTP<Input maxLength={6} value={otp} onChange={e=>setOtp(e.target.value)}/></label><label>New password<Input type="password" value={newPassword} onChange={e=>setPassword(e.target.value)}/></label><Button>Reset password</Button></form>}</AuthShell>}
export function VerifyEmailPage(){return <AuthShell title="Verify your email" subtitle="Email verification foundation is ready"><div className="success-panel"><BrainCircuit/><p className="muted">Paste the verification token through the API during development. The full email-link screen will be connected when an email provider is selected.</p><Link to="/login">Go to login</Link></div></AuthShell>}
function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="auth-page"><div className="auth-visual"><div className="brand large"><span className="brand-mark">E</span><span>Edvixa</span></div><h1>Learn smarter.<br/>Grow faster.</h1><p>AI-powered practice, progress tracking, and expert teacher sessions in one platform.</p><div className="orb orb-one"/><div className="orb orb-two"/></div><Card className="auth-card"><h2>{title}</h2><p className="muted">{subtitle}</p>{children}</Card></div>}
