import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Save, Settings2, TriangleAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Button, Card, Input } from '../../../components/ui'
import { getAdminData, getApiError, patchAdminData } from '../api'
import { AdminError, AdminLoading, AdminPageHeader } from '../components'
import type { PlatformSettings } from '../types'

type FormState=Omit<PlatformSettings,'_id'|'updatedAt'>
export default function AdminSettingsPage(){
  const client=useQueryClient();const [form,setForm]=useState<FormState|null>(null),[notice,setNotice]=useState('')
  const query=useQuery({queryKey:['admin','settings'],queryFn:()=>getAdminData<PlatformSettings>('/admin/settings')})
  useEffect(()=>{if(query.data){const {_id:_id,updatedAt:_updatedAt,...rest}=query.data;setForm(rest)}},[query.data])
  const mutation=useMutation({mutationFn:()=>patchAdminData<PlatformSettings>('/admin/settings',form),onSuccess:async(data)=>{setNotice('Platform settings saved and recorded in the audit log.');setForm((({_id:_id,updatedAt:_updatedAt,...rest})=>rest)(data));await client.invalidateQueries({queryKey:['admin','settings']})}})
  if(query.isLoading||!form)return <><AdminPageHeader title="Platform settings" subtitle="Control registration, maintenance, scheduling, and payment policy."/><AdminLoading/></>
  if(query.isError)return <><AdminPageHeader title="Platform settings" subtitle="Control registration, maintenance, scheduling, and payment policy."/><AdminError message={getApiError(query.error)} onRetry={()=>query.refetch()}/></>
  return <div className="admin-page"><AdminPageHeader title="Platform settings" subtitle="Control registration, maintenance, scheduling, and payment policy." actions={<Button onClick={()=>mutation.mutate()} disabled={mutation.isPending}><Save size={16}/>{mutation.isPending?'Saving…':'Save settings'}</Button>}/>{notice&&<div className="alert success">{notice}</div>}{mutation.isError&&<div className="alert error">{getApiError(mutation.error)}</div>}
    {form.maintenanceMode&&<div className="admin-maintenance-warning"><TriangleAlert/><div><strong>Maintenance mode is enabled</strong><p>New public operations should be treated as paused until this setting is disabled.</p></div></div>}
    <div className="admin-settings-grid"><Card><div className="admin-section-heading"><Settings2/><div><h3>Brand and support</h3><p className="muted">User-facing platform identity and operational contact.</p></div></div><div className="form"><label>Platform name<Input required minLength={2} maxLength={80} value={form.platformName} onChange={(event)=>setForm(value=>value&&({...value,platformName:event.target.value}))}/></label><label>Support email<Input type="email" required value={form.supportEmail} onChange={(event)=>setForm(value=>value&&({...value,supportEmail:event.target.value}))}/></label><label>Default timezone<Input required value={form.defaultTimezone} onChange={(event)=>setForm(value=>value&&({...value,defaultTimezone:event.target.value}))}/></label></div></Card><Card><h3>Access policy</h3><div className="admin-toggle-list"><Toggle label="Maintenance mode" description="Signal a controlled maintenance window." checked={form.maintenanceMode} onChange={checked=>setForm({...form,maintenanceMode:checked})}/><Toggle label="Allow new registrations" description="Accept new student and teacher accounts." checked={form.allowRegistrations} onChange={checked=>setForm({...form,allowRegistrations:checked})}/><Toggle label="Allow teacher applications" description="Permit teachers to submit profiles for approval." checked={form.allowTeacherApplications} onChange={checked=>setForm({...form,allowTeacherApplications:checked})}/></div></Card><Card><h3>Booking policy</h3><div className="form"><label>Minimum booking notice (hours)<Input type="number" min={0} max={168} value={form.minimumBookingNoticeHours} onChange={(event)=>setForm({...form,minimumBookingNoticeHours:Number(event.target.value)})}/></label><label>Maximum advance window (days)<Input type="number" min={1} max={365} value={form.maximumBookingAdvanceDays} onChange={(event)=>setForm({...form,maximumBookingAdvanceDays:Number(event.target.value)})}/></label></div></Card><Card><h3>Payments</h3><div className="form"><label>Platform fee percentage<Input type="number" min={0} max={100} step="0.1" value={form.platformFeePercent} onChange={(event)=>setForm({...form,platformFeePercent:Number(event.target.value)})}/></label><p className="muted">Changes apply to newly calculated bookings; historical fee records are never rewritten.</p></div></Card></div>
  </div>
}
function Toggle({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="admin-toggle"><div><strong>{label}</strong><p className="muted">{description}</p></div><input type="checkbox" checked={checked} onChange={(event)=>onChange(event.target.checked)}/><span/></label>}
