import { useQuery } from '@tanstack/react-query'
import { Ban, KeyRound, Search, ShieldCheck, TimerReset, UserRoundX } from 'lucide-react'
import { useState } from 'react'
import { Card, Input, StatCard } from '../../../components/ui'
import { formatDate, getAdminData, getApiError } from '../api'
import { AdminEmpty, AdminError, AdminLoading, AdminPageHeader, AdminPagination, AdminTable, StatusBadge } from '../components'
import type { AdminAuditLog, Paginated } from '../types'

type Security={activeSessions:number;revokedSessions:number;unverifiedUsers:number;bannedUsers:number;expiredSessions:number;controls:Record<string,string|boolean>;recentAdminActions:AdminAuditLog[]}
export default function AdminSecurityPage(){
  const [page,setPage]=useState(1),[searchDraft,setSearchDraft]=useState(''),[search,setSearch]=useState(''),[action,setAction]=useState('')
  const overview=useQuery({queryKey:['admin','security'],queryFn:()=>getAdminData<Security>('/admin/security')})
  const logs=useQuery({queryKey:['admin','audit',{page,search,action}],queryFn:()=>getAdminData<Paginated<AdminAuditLog>>('/admin/audit-logs',{page,limit:20,search:search||undefined,action:action||undefined})})
  return <div className="admin-page"><AdminPageHeader title="Security and audit" subtitle="Review active sessions, security controls, and immutable administrative activity records."/>
    {overview.isLoading?<AdminLoading rows={4}/>:overview.isError||!overview.data?<AdminError message={getApiError(overview.error)} onRetry={()=>overview.refetch()}/>:<><div className="admin-metric-grid admin-metric-grid-five"><StatCard label="Active sessions" value={overview.data.activeSessions} icon={<KeyRound/>}/><StatCard label="Revoked sessions" value={overview.data.revokedSessions} icon={<TimerReset/>}/><StatCard label="Expired sessions" value={overview.data.expiredSessions} icon={<TimerReset/>}/><StatCard label="Unverified users" value={overview.data.unverifiedUsers} icon={<UserRoundX/>}/><StatCard label="Banned accounts" value={overview.data.bannedUsers} icon={<Ban/>}/></div><Card><div className="row-between"><div><h3>Application security controls</h3><p className="muted">Controls reported by the running API implementation.</p></div><ShieldCheck/></div><div className="admin-control-grid">{Object.entries(overview.data.controls).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g,' $1')}</span><strong>{typeof value==='boolean'?(value?'Enabled':'Disabled'):value}</strong></div>)}</div></Card></>}
    <Card><div className="row-between"><div><h3>Administrative audit log</h3><p className="muted">Search by summary, target, request ID, or exact action key.</p></div></div><form className="admin-search-row" onSubmit={(event)=>{event.preventDefault();setPage(1);setSearch(searchDraft.trim())}}><label><Search size={16}/><Input value={searchDraft} onChange={(event)=>setSearchDraft(event.target.value)} placeholder="Search audit entries"/></label><Input value={action} onChange={(event)=>{setAction(event.target.value);setPage(1)}} placeholder="Action, e.g. user.ban"/><button className="button">Apply</button></form>{logs.isLoading?<AdminLoading/>:logs.isError?<AdminError message={getApiError(logs.error)} onRetry={()=>logs.refetch()}/>:!logs.data||logs.data.items.length===0?<AdminEmpty title="No audit entries" message="Administrative changes will appear here automatically."/>:<><AdminTable headers={['When','Administrator','Action','Target','Summary','Request ID']}>{logs.data.items.map(entry=><tr key={entry._id}><td>{formatDate(entry.createdAt,true)}</td><td><strong>{entry.actorId?.name??'Administrator'}</strong><small>{entry.actorId?.email}</small></td><td><code>{entry.action}</code></td><td><StatusBadge value={entry.targetType}/><small>{entry.targetId??'—'}</small></td><td>{entry.summary}</td><td><code>{entry.requestId??'—'}</code></td></tr>)}</AdminTable><AdminPagination pagination={logs.data.pagination} onPage={setPage}/></>}</Card>
  </div>
}
