import { useQuery } from '@tanstack/react-query'
import { BarChart3, BookOpenCheck, CalendarDays, IndianRupee, UserPlus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Card, StatCard } from '../../../components/ui'
import { formatMoney, getAdminData, getApiError } from '../api'
import { AdminError, AdminLoading, AdminPageHeader, StatusBadge } from '../components'

type Analytics={range:string;series:Array<{key:string;label:string;users:number;bookings:number;revenue:number;practice:number}>;roleSplit:Array<{label:string;value:number}>;bookingStatus:Array<{label:string;value:number}>;subjectUsage:Array<{label:string;value:number}>}
export default function AdminAnalyticsPage(){
  const [range,setRange]=useState<'7d'|'30d'|'90d'|'12m'>('30d')
  const query=useQuery({queryKey:['admin','analytics',range],queryFn:()=>getAdminData<Analytics>('/admin/analytics',{range})})
  const totals=useMemo(()=>query.data?.series.reduce((sum,item)=>({users:sum.users+item.users,bookings:sum.bookings+item.bookings,revenue:sum.revenue+item.revenue,practice:sum.practice+item.practice}),{users:0,bookings:0,revenue:0,practice:0}),[query.data])
  const max=useMemo(()=>Math.max(1,...(query.data?.series.map(item=>Math.max(item.users,item.bookings,item.practice))??[1])),[query.data])
  return <div className="admin-page"><AdminPageHeader title="Platform analytics" subtitle="Measure user acquisition, practice usage, bookings, revenue, and curriculum demand." actions={<select className="input admin-range-select" value={range} onChange={(event)=>setRange(event.target.value as typeof range)}><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="12m">Last 12 months</option></select>}/>
    {query.isLoading?<AdminLoading rows={6}/>:query.isError||!query.data?<AdminError message={getApiError(query.error)} onRetry={()=>query.refetch()}/>:<><div className="admin-metric-grid admin-metric-grid-four"><StatCard label="New users" value={totals?.users??0} icon={<UserPlus/>}/><StatCard label="Bookings created" value={totals?.bookings??0} icon={<CalendarDays/>}/><StatCard label="Practice sessions" value={totals?.practice??0} icon={<BookOpenCheck/>}/><StatCard label="Paid revenue" value={formatMoney(totals?.revenue)} icon={<IndianRupee/>}/></div><Card className="admin-chart-card"><div className="row-between"><div><h3>Activity over time</h3><p className="muted">Relative daily/monthly volume for users, bookings, and practice</p></div><BarChart3/></div><div className="admin-line-bars">{query.data.series.map(item=><div className="admin-line-bar-group" key={item.key}><div className="admin-line-bar-stack"><span className="users" style={{height:`${Math.max(3,item.users/max*100)}%`}}/><span className="bookings" style={{height:`${Math.max(3,item.bookings/max*100)}%`}}/><span className="practice" style={{height:`${Math.max(3,item.practice/max*100)}%`}}/></div><small>{item.label}</small></div>)}</div><div className="admin-chart-legend"><span><i className="users"/>Users</span><span><i className="bookings"/>Bookings</span><span><i className="practice"/>Practice</span></div></Card><div className="admin-dashboard-grid admin-analytics-splits"><Breakdown title="Account roles" rows={query.data.roleSplit}/><Breakdown title="Booking lifecycle" rows={query.data.bookingStatus}/><Breakdown title="Most booked subjects" rows={query.data.subjectUsage}/></div></>}
  </div>
}
function Breakdown({title,rows}:{title:string;rows:Array<{label:string;value:number}>}){const total=Math.max(1,rows.reduce((sum,row)=>sum+row.value,0));return <Card><h3>{title}</h3><div className="admin-breakdown-list">{rows.length===0?<p className="muted">No data yet.</p>:rows.map(row=><div key={row.label}><div className="row-between"><StatusBadge value={row.label}/><strong>{row.value}</strong></div><div className="progress"><span style={{width:`${row.value/total*100}%`}}/></div></div>)}</div></Card>}
