import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Megaphone, Pencil, Plus } from 'lucide-react'
import { useState } from 'react'
import { Button, Card, Input } from '../../../components/ui'
import { formatDate, getAdminData, getApiError, patchAdminData, postAdminData } from '../api'
import { AdminEmpty, AdminError, AdminLoading, AdminModal, AdminPageHeader, AdminPagination, StatusBadge } from '../components'
import type { AdminAnnouncement, Paginated } from '../types'

type Draft={title:string;message:string;audience:'all'|'student'|'teacher';severity:'info'|'success'|'warning'|'critical';status:'draft'|'published'|'archived';publishAt:string;expiresAt:string}
const blank=():Draft=>({title:'',message:'',audience:'all',severity:'info',status:'draft',publishAt:'',expiresAt:''})
const localValue=(value?:string|null)=>value?new Date(new Date(value).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''
export default function AdminAnnouncementsPage(){
  const client=useQueryClient();const [page,setPage]=useState(1),[status,setStatus]=useState('all'),[audience,setAudience]=useState('all'),[editing,setEditing]=useState<AdminAnnouncement|null>(null),[open,setOpen]=useState(false),[draft,setDraft]=useState<Draft>(blank()),[notice,setNotice]=useState('')
  const query=useQuery({queryKey:['admin','announcements',{page,status,audience}],queryFn:()=>getAdminData<Paginated<AdminAnnouncement>>('/admin/announcements',{page,limit:12,status,audience:audience==='all'?undefined:audience})})
  const mutation=useMutation({mutationFn:()=>{const body={...draft,publishAt:draft.publishAt?new Date(draft.publishAt).toISOString():null,expiresAt:draft.expiresAt?new Date(draft.expiresAt).toISOString():null};return editing?patchAdminData(`/admin/announcements/${editing._id}`,body):postAdminData('/admin/announcements',body)},onSuccess:async()=>{setNotice(editing?'Announcement updated.':'Announcement created.');close();await client.invalidateQueries({queryKey:['admin','announcements']})}})
  const close=()=>{setOpen(false);setEditing(null);setDraft(blank())}
  const create=()=>{setEditing(null);setDraft(blank());setOpen(true);setNotice('')}
  const edit=(item:AdminAnnouncement)=>{setEditing(item);setDraft({title:item.title,message:item.message,audience:item.audience,severity:item.severity,status:item.status,publishAt:localValue(item.publishAt),expiresAt:localValue(item.expiresAt)});setOpen(true);setNotice('')}
  return <div className="admin-page"><AdminPageHeader title="Announcements" subtitle="Publish targeted platform notices for students, teachers, or everyone." actions={<Button onClick={create}><Plus size={16}/>Create announcement</Button>}/>{notice&&<div className="alert success">{notice}</div>}
    <Card className="admin-filter-card"><div className="admin-compact-filters"><label>Status<select className="input" value={status} onChange={(event)=>{setStatus(event.target.value);setPage(1)}}><option value="all">All statuses</option>{['draft','published','archived'].map(value=><option key={value}>{value}</option>)}</select></label><label>Audience<select className="input" value={audience} onChange={(event)=>{setAudience(event.target.value);setPage(1)}}><option value="all">All audiences</option><option value="student">Students</option><option value="teacher">Teachers</option></select></label></div></Card>
    {query.isLoading?<AdminLoading/>:query.isError?<AdminError message={getApiError(query.error)} onRetry={()=>query.refetch()}/>:!query.data||query.data.items.length===0?<AdminEmpty title="No announcements" message="Create a draft or publish a notice to platform users."/>:<><div className="admin-announcement-grid">{query.data.items.map(item=><Card key={item._id} className={`admin-announcement-card severity-${item.severity}`}><div className="row-between"><Megaphone/><div className="admin-chip-list"><StatusBadge value={item.status}/><StatusBadge value={item.audience}/></div></div><h3>{item.title}</h3><p>{item.message}</p><dl className="admin-definition-grid"><div><dt>Publish</dt><dd>{formatDate(item.publishAt,true)}</dd></div><div><dt>Expires</dt><dd>{formatDate(item.expiresAt,true)}</dd></div><div><dt>Created by</dt><dd>{item.createdBy?.name??'Administrator'}</dd></div><div><dt>Updated</dt><dd>{formatDate(item.updatedAt,true)}</dd></div></dl><Button className="button-secondary" onClick={()=>edit(item)}><Pencil size={16}/>Edit</Button></Card>)}</div><AdminPagination pagination={query.data.pagination} onPage={setPage}/></>}
    {open&&<AdminModal title={editing?'Edit announcement':'New announcement'} onClose={close}><form className="form" onSubmit={(event)=>{event.preventDefault();mutation.mutate()}}><label>Title<Input required minLength={3} maxLength={140} value={draft.title} onChange={(event)=>setDraft(value=>({...value,title:event.target.value}))}/></label><label>Message<textarea className="input admin-textarea admin-textarea-tall" required minLength={3} maxLength={2000} value={draft.message} onChange={(event)=>setDraft(value=>({...value,message:event.target.value}))}/></label><div className="admin-form-grid"><label>Audience<select className="input" value={draft.audience} onChange={(event)=>setDraft(value=>({...value,audience:event.target.value as Draft['audience']}))}><option value="all">Everyone</option><option value="student">Students</option><option value="teacher">Teachers</option></select></label><label>Severity<select className="input" value={draft.severity} onChange={(event)=>setDraft(value=>({...value,severity:event.target.value as Draft['severity']}))}>{['info','success','warning','critical'].map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select className="input" value={draft.status} onChange={(event)=>setDraft(value=>({...value,status:event.target.value as Draft['status']}))}>{['draft','published','archived'].map(value=><option key={value}>{value}</option>)}</select></label><label>Publish at<Input type="datetime-local" value={draft.publishAt} onChange={(event)=>setDraft(value=>({...value,publishAt:event.target.value}))}/></label><label>Expires at<Input type="datetime-local" value={draft.expiresAt} onChange={(event)=>setDraft(value=>({...value,expiresAt:event.target.value}))}/></label></div>{mutation.isError&&<div className="alert error">{getApiError(mutation.error)}</div>}<div className="button-row"><Button type="button" className="button-secondary" onClick={close}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save announcement'}</Button></div></form></AdminModal>}
  </div>
}
