import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BookPlus, Pencil, Power, Plus, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Button, Card, Input } from '../../../components/ui'
import { api } from '../../../lib/api'
import { getAdminData, getApiError, postAdminData } from '../api'
import { AdminEmpty, AdminError, AdminLoading, AdminModal, AdminPageHeader, StatusBadge } from '../components'
import type { AdminSubject, SubjectTopic } from '../types'

type SubjectDraft = Omit<AdminSubject,'_id'>
const emptyTopic=():SubjectTopic=>({name:'',description:'',difficultyLevel:1,isAiEnabled:true,order:0,isActive:true})
const emptySubject=():SubjectDraft=>({name:'',slug:'',description:'',gradeLevels:[],topics:[],isActive:true,isAiEnabled:true})
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')

export default function AdminSubjectsPage(){
  const client=useQueryClient(); const [editing,setEditing]=useState<AdminSubject|null>(null); const [creating,setCreating]=useState(false); const [draft,setDraft]=useState<SubjectDraft>(emptySubject()); const [gradeText,setGradeText]=useState(''); const [notice,setNotice]=useState('')
  const query=useQuery({queryKey:['admin','subjects'],queryFn:()=>getAdminData<AdminSubject[]>('/admin/subjects')})
  const save=useMutation({mutationFn:async()=>{const payload={...draft,gradeLevels:gradeText.split(',').map(v=>v.trim()).filter(Boolean),topics:draft.topics.map((topic,index)=>({...topic,order:index}))};if(editing){const response=await api.patch(`/subjects/${editing._id}`,payload);return response.data}return postAdminData('/subjects',payload)},onSuccess:async()=>{setNotice(editing?'Subject updated.':'Subject created.');close();await client.invalidateQueries({queryKey:['admin','subjects']})}})
  const deactivate=useMutation({mutationFn:async(subject:AdminSubject)=>subject.isActive?api.delete(`/subjects/${subject._id}`):api.patch(`/subjects/${subject._id}`,{isActive:true}),onSuccess:async()=>{setNotice('Subject availability updated.');await client.invalidateQueries({queryKey:['admin','subjects']})}})
  const close=()=>{setEditing(null);setCreating(false);setDraft(emptySubject());setGradeText('')}
  const openCreate=()=>{setEditing(null);setCreating(true);setDraft(emptySubject());setGradeText('');setNotice('')}
  const openEdit=(subject:AdminSubject)=>{setEditing(subject);setCreating(false);setDraft({name:subject.name,slug:subject.slug,description:subject.description??'',gradeLevels:subject.gradeLevels??[],topics:(subject.topics??[]).map(t=>({...t})),isActive:subject.isActive,isAiEnabled:subject.isAiEnabled});setGradeText((subject.gradeLevels??[]).join(', '));setNotice('')}
  const activeCount=useMemo(()=>query.data?.filter(subject=>subject.isActive).length??0,[query.data])
  const updateTopic=(index:number,patch:Partial<SubjectTopic>)=>setDraft(value=>({...value,topics:value.topics.map((topic,i)=>i===index?{...topic,...patch}:topic)}))
  return <div className="admin-page"><AdminPageHeader title="Subjects and AI curriculum" subtitle="Create subjects, define grade availability, and control AI-enabled practice topics." actions={<Button onClick={openCreate}><BookPlus size={17}/>New subject</Button>}/>{notice&&<div className="alert success">{notice}</div>}
    {query.data&&<p className="muted admin-result-summary">{activeCount} active subjects · {query.data.reduce((sum,subject)=>sum+(subject.topics?.length??0),0)} configured topics</p>}
    {query.isLoading?<AdminLoading/>:query.isError?<AdminError message={getApiError(query.error)} onRetry={()=>query.refetch()}/>:!query.data||query.data.length===0?<AdminEmpty title="No subjects configured" message="Create the first subject to enable teacher profiles and student practice."/>:<div className="admin-subject-grid">{query.data.map(subject=><Card key={subject._id} className="admin-subject-card"><div className="row-between"><div><h3>{subject.name}</h3><p className="muted">/{subject.slug}</p></div><StatusBadge value={subject.isActive}/></div><p>{subject.description||'No description has been added.'}</p><div className="admin-chip-list">{subject.gradeLevels?.map(grade=><span key={grade}>{grade}</span>)}</div><div className="admin-subject-meta"><span>{subject.topics?.length??0} topics</span><span>AI {subject.isAiEnabled?'enabled':'disabled'}</span></div><div className="button-row"><Button className="button-secondary" onClick={()=>openEdit(subject)}><Pencil size={16}/>Edit</Button><Button className={subject.isActive?'button-danger':'button-secondary'} onClick={()=>deactivate.mutate(subject)} disabled={deactivate.isPending}>{subject.isActive?<><Power size={16}/>Deactivate</>:<><Power size={16}/>Reactivate</>}</Button></div></Card>)}</div>}
    {(creating||editing)&&<AdminModal title={editing?`Edit ${editing.name}`:'Create subject'} onClose={close}><form className="form admin-subject-form" onSubmit={(event)=>{event.preventDefault();save.mutate()}}><div className="admin-form-grid"><label>Name<Input required minLength={2} value={draft.name} onChange={(event)=>setDraft(value=>({...value,name:event.target.value,...(!editing?{slug:slugify(event.target.value)}:{})}))}/></label><label>Slug<Input required pattern="[a-z0-9-]+" value={draft.slug} onChange={(event)=>setDraft(value=>({...value,slug:slugify(event.target.value)}))}/></label></div><label>Description<textarea className="input admin-textarea" value={draft.description} onChange={(event)=>setDraft(value=>({...value,description:event.target.value}))}/></label><label>Grade levels <small className="muted">Comma separated</small><Input value={gradeText} onChange={(event)=>setGradeText(event.target.value)} placeholder="Grade 8, Grade 9, Grade 10"/></label><div className="admin-check-grid"><label><input type="checkbox" checked={draft.isActive} onChange={(event)=>setDraft(value=>({...value,isActive:event.target.checked}))}/> Active</label><label><input type="checkbox" checked={draft.isAiEnabled} onChange={(event)=>setDraft(value=>({...value,isAiEnabled:event.target.checked}))}/> AI practice enabled</label></div><div className="row-between"><div><h3>Topics</h3><p className="muted">Control difficulty and AI availability per topic.</p></div><Button type="button" className="button-secondary" onClick={()=>setDraft(value=>({...value,topics:[...value.topics,emptyTopic()]}))}><Plus size={16}/>Add topic</Button></div><div className="admin-topic-editor">{draft.topics.map((topic,index)=><div className="admin-topic-row" key={`${topic._id??'new'}-${index}`}><Input required minLength={2} value={topic.name} onChange={(event)=>updateTopic(index,{name:event.target.value})} placeholder="Topic name"/><Input value={topic.description} onChange={(event)=>updateTopic(index,{description:event.target.value})} placeholder="Description"/><select className="input" value={topic.difficultyLevel} onChange={(event)=>updateTopic(index,{difficultyLevel:Number(event.target.value)})}>{[1,2,3,4,5].map(value=><option value={value} key={value}>Difficulty {value}</option>)}</select><label className="admin-inline-check"><input type="checkbox" checked={topic.isAiEnabled} onChange={(event)=>updateTopic(index,{isAiEnabled:event.target.checked})}/>AI</label><Button type="button" className="button-danger" onClick={()=>setDraft(value=>({...value,topics:value.topics.filter((_,i)=>i!==index)}))}><Trash2 size={16}/></Button></div>)}</div>{save.isError&&<div className="alert error">{getApiError(save.error)}</div>}<div className="button-row"><Button type="button" className="button-secondary" onClick={close}>Cancel</Button><Button disabled={save.isPending}>{save.isPending?'Saving…':'Save subject'}</Button></div></form></AdminModal>}
  </div>
}
