import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { LifeBuoy, Search } from 'lucide-react'
import { useState } from 'react'
import { Button, Card, Input } from '../../../components/ui'
import { formatDate, getAdminData, getApiError, patchAdminData } from '../api'
import { AdminEmpty, AdminError, AdminLoading, AdminModal, AdminPageHeader, AdminPagination, AdminTable, StatusBadge } from '../components'
import type { Paginated, SupportTicket } from '../types'

export default function AdminSupportPage(){
  const client=useQueryClient();const [page,setPage]=useState(1),[searchDraft,setSearchDraft]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[priority,setPriority]=useState('all'),[selected,setSelected]=useState<SupportTicket|null>(null),[nextStatus,setNextStatus]=useState<SupportTicket['status']>('in_progress'),[nextPriority,setNextPriority]=useState<SupportTicket['priority']>('normal'),[resolution,setResolution]=useState(''),[notice,setNotice]=useState('')
  const query=useQuery({queryKey:['admin','support',{page,search,status,priority}],queryFn:()=>getAdminData<Paginated<SupportTicket>>('/admin/support',{page,limit:20,search:search||undefined,status,priority})})
  const mutation=useMutation({mutationFn:()=>patchAdminData(`/admin/support/${selected?._id}`,{status:nextStatus,priority:nextPriority,resolution:resolution.trim()}),onSuccess:async()=>{setNotice('Support ticket updated.');setSelected(null);await client.invalidateQueries({queryKey:['admin','support']})}})
  const open=(ticket:SupportTicket)=>{setSelected(ticket);setNextStatus(ticket.status);setNextPriority(ticket.priority);setResolution(ticket.resolution??'');setNotice('')}
  return <div className="admin-page"><AdminPageHeader title="Support centre" subtitle="Triage requests, assign priority, record resolutions, and track ticket progress."/>{notice&&<div className="alert success">{notice}</div>}<Card className="admin-filter-card"><form className="admin-filter-grid" onSubmit={(event)=>{event.preventDefault();setPage(1);setSearch(searchDraft.trim())}}><label>Search<Input value={searchDraft} onChange={(event)=>setSearchDraft(event.target.value)} placeholder="Requester, email, subject, or message"/></label><label>Status<select className="input" value={status} onChange={(event)=>{setStatus(event.target.value);setPage(1)}}><option value="all">All statuses</option>{['open','in_progress','resolved','closed'].map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label>Priority<select className="input" value={priority} onChange={(event)=>{setPriority(event.target.value);setPage(1)}}><option value="all">All priorities</option>{['low','normal','high','urgent'].map(value=><option key={value}>{value}</option>)}</select></label><Button><Search size={16}/>Apply</Button></form></Card>
    {query.isLoading?<AdminLoading/>:query.isError?<AdminError message={getApiError(query.error)} onRetry={()=>query.refetch()}/>:!query.data||query.data.items.length===0?<AdminEmpty title="No support tickets" message="New user support requests will appear in this queue."/>:<Card><AdminTable headers={['Ticket','Requester','Category','Priority','Status','Created','Action']}>{query.data.items.map(ticket=><tr key={ticket._id}><td><strong>{ticket.subject}</strong><small>{ticket.message.length>100?`${ticket.message.slice(0,100)}…`:ticket.message}</small></td><td><strong>{ticket.requesterName}</strong><small>{ticket.requesterEmail} · {ticket.requesterRole}</small></td><td>{ticket.category}</td><td><StatusBadge value={ticket.priority}/></td><td><StatusBadge value={ticket.status}/></td><td>{formatDate(ticket.createdAt,true)}</td><td><Button className="button-secondary" onClick={()=>open(ticket)}><LifeBuoy size={16}/>Manage</Button></td></tr>)}</AdminTable><AdminPagination pagination={query.data.pagination} onPage={setPage}/></Card>}
    {selected&&<AdminModal title={selected.subject} onClose={()=>setSelected(null)}><div className="admin-ticket-message"><strong>Message from {selected.requesterName}</strong><p>{selected.message}</p></div><form className="form" onSubmit={(event)=>{event.preventDefault();mutation.mutate()}}><div className="admin-form-grid"><label>Status<select className="input" value={nextStatus} onChange={(event)=>setNextStatus(event.target.value as SupportTicket['status'])}>{['open','in_progress','resolved','closed'].map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label>Priority<select className="input" value={nextPriority} onChange={(event)=>setNextPriority(event.target.value as SupportTicket['priority'])}>{['low','normal','high','urgent'].map(value=><option key={value}>{value}</option>)}</select></label></div><label>Resolution / internal response<textarea className="input admin-textarea admin-textarea-tall" maxLength={3000} value={resolution} onChange={(event)=>setResolution(event.target.value)} placeholder="Document the investigation and resolution."/></label>{mutation.isError&&<div className="alert error">{getApiError(mutation.error)}</div>}<div className="button-row"><Button type="button" className="button-secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Update ticket'}</Button></div></form></AdminModal>}
  </div>
}
