import { useQuery } from '@tanstack/react-query'
import { GraduationCap, ShieldCheck, UserRoundCheck } from 'lucide-react'
import { Card } from '../../../components/ui'
import { getAdminData, getApiError } from '../api'
import { AdminError, AdminLoading, AdminPageHeader, StatusBadge } from '../components'

type RoleInfo={roles:Array<{role:'student'|'teacher'|'admin';description:string;permissions:string[]}>;policy:{serverEnforced:boolean;adminCreation:string;selfServiceRoleChange:boolean;leastPrivilege:boolean}}
const icons={student:GraduationCap,teacher:UserRoundCheck,admin:ShieldCheck}
export default function AdminRolesPage(){const query=useQuery({queryKey:['admin','roles'],queryFn:()=>getAdminData<RoleInfo>('/admin/roles')});return <div className="admin-page"><AdminPageHeader title="Roles and permissions" subtitle="Read-only view of the server-enforced authorization model and least-privilege policy."/>{query.isLoading?<AdminLoading/>:query.isError||!query.data?<AdminError message={getApiError(query.error)} onRetry={()=>query.refetch()}/>:<><div className="admin-role-grid">{query.data.roles.map(role=>{const Icon=icons[role.role];return <Card key={role.role} className="admin-role-card"><div className="admin-role-icon"><Icon/></div><div className="row-between"><h3>{role.role.replace(/^./,value=>value.toUpperCase())}</h3><StatusBadge value={role.role}/></div><p className="muted">{role.description}</p><div className="admin-permission-list">{role.permissions.map(permission=><code key={permission}>{permission}</code>)}</div></Card>})}</div><Card><h3>Authorization safeguards</h3><dl className="admin-definition-grid admin-policy-grid"><div><dt>Server enforced</dt><dd>{query.data.policy.serverEnforced?'Yes':'No'}</dd></div><div><dt>Admin creation</dt><dd>{query.data.policy.adminCreation.replaceAll('-',' ')}</dd></div><div><dt>Self-service role changes</dt><dd>{query.data.policy.selfServiceRoleChange?'Allowed':'Blocked'}</dd></div><div><dt>Least privilege</dt><dd>{query.data.policy.leastPrivilege?'Enabled':'Disabled'}</dd></div></dl><p className="muted">This page intentionally does not provide a client-side permission editor. Role authorization belongs to reviewed server code, not mutable browser configuration.</p></Card></>}</div>}
