import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Ban, CheckCircle2, Search, ShieldCheck, UserCheck, UserX } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Button, Card, Input } from '../../../components/ui'
import { formatDate, getAdminData, getApiError, patchAdminData } from '../api'
import { AdminEmpty, AdminError, AdminLoading, AdminModal, AdminPageHeader, AdminPagination, AdminTable, StatusBadge } from '../components'
import type { AdminUser, Paginated } from '../types'

type UserAction = 'activate' | 'deactivate' | 'ban' | 'unban' | 'verify-email'

export default function AdminUsersPage() {
  const client = useQueryClient()
  const [page,setPage]=useState(1), [searchDraft,setSearchDraft]=useState(''), [search,setSearch]=useState('')
  const [role,setRole]=useState('all'), [status,setStatus]=useState('all'), [sort,setSort]=useState('newest')
  const [selected,setSelected]=useState<AdminUser|null>(null), [action,setAction]=useState<UserAction>('activate'), [reason,setReason]=useState(''), [notice,setNotice]=useState('')
  const query=useQuery({queryKey:['admin','users',{page,search,role,status,sort}],queryFn:()=>getAdminData<Paginated<AdminUser>>('/admin/users',{page,limit:20,search:search||undefined,role,status,sort})})
  const mutation=useMutation({mutationFn:()=>patchAdminData(`/admin/users/${selected?._id}/action`,{action,...(['ban','deactivate'].includes(action)?{reason}: {})}),onSuccess:async()=>{setNotice(`Account action “${action}” completed.`);setSelected(null);setReason('');await client.invalidateQueries({queryKey:['admin','users']})}})
  const open=(user:AdminUser,next:UserAction)=>{setSelected(user);setAction(next);setReason('');setNotice('')}
  const submit=(event:React.FormEvent)=>{event.preventDefault();mutation.mutate()}

  return <div className="admin-page"><AdminPageHeader title="User management" subtitle="Search, verify, activate, deactivate, or ban platform accounts."/>
    {notice&&<div className="alert success">{notice}</div>}
    <Card className="admin-filter-card"><form className="admin-filter-grid" onSubmit={(event)=>{event.preventDefault();setPage(1);setSearch(searchDraft.trim())}}><label>Search<Input value={searchDraft} onChange={(event)=>setSearchDraft(event.target.value)} placeholder="Name, email, or phone"/></label><label>Role<select className="input" value={role} onChange={(event)=>{setRole(event.target.value);setPage(1)}}><option value="all">All roles</option><option value="student">Students</option><option value="teacher">Teachers</option><option value="admin">Admins</option></select></label><label>Status<select className="input" value={status} onChange={(event)=>{setStatus(event.target.value);setPage(1)}}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="banned">Banned</option><option value="unverified">Unverified</option></select></label><label>Sort<select className="input" value={sort} onChange={(event)=>setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name</option><option value="lastLogin">Last login</option></select></label><Button><Search size={16}/>Apply</Button></form></Card>
    {query.isLoading?<AdminLoading/>:query.isError?<AdminError onRetry={()=>query.refetch()}/>:!query.data||query.data.items.length===0?<AdminEmpty title="No matching users" message="Try changing the search or status filters."/>:<Card><AdminTable headers={['User','Role','Verification','Account','Last login','Joined','Actions']}>{query.data.items.map((user)=><tr key={user._id}><td><Link to={`/admin/users/${user._id}`}><strong>{user.name}</strong><small>{user.email}</small></Link></td><td><StatusBadge value={user.role}/></td><td><StatusBadge value={user.isEmailVerified?'verified':'unverified'}/></td><td><StatusBadge value={user.bannedAt?'banned':user.isActive?'active':'inactive'}/></td><td>{formatDate(user.lastLoginAt,true)}</td><td>{formatDate(user.createdAt)}</td><td><div className="admin-row-actions"><Link className="button button-secondary" to={`/admin/users/${user._id}`}>View</Link>{!user.isEmailVerified&&<Button className="button-secondary" onClick={()=>open(user,'verify-email')} title="Verify email"><ShieldCheck size={16}/></Button>}{user.bannedAt?<Button onClick={()=>open(user,'unban')}><UserCheck size={16}/></Button>:user.isActive?<><Button className="button-secondary" onClick={()=>open(user,'deactivate')} title="Deactivate"><UserX size={16}/></Button><Button className="button-danger" onClick={()=>open(user,'ban')} title="Ban"><Ban size={16}/></Button></>:<Button onClick={()=>open(user,'activate')}><CheckCircle2 size={16}/>Activate</Button>}</div></td></tr>)}</AdminTable><AdminPagination pagination={query.data.pagination} onPage={setPage}/></Card>}
    {selected&&<AdminModal title={`${action.replaceAll('-',' ')} ${selected.name}`} onClose={()=>setSelected(null)}><form className="form" onSubmit={submit}><p className="muted">This action affects <strong>{selected.email}</strong>. Protected admin accounts cannot be disabled by another administrator.</p>{['ban','deactivate'].includes(action)&&<label>Reason<textarea className="input admin-textarea" required minLength={3} maxLength={500} value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Explain why this account action is necessary."/></label>}{mutation.isError&&<div className="alert error">{getApiError(mutation.error)}</div>}<div className="button-row"><Button type="button" className="button-secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Confirm action'}</Button></div></form></AdminModal>}
  </div>
}
